# Tile configuration
# This file defines all tile classes and tile definitions.
# Its contents are shared across all map files.

CLASSES
F:floor:false
W:wall:true

TILES
F00:floor:floor/dirt0.png
F01:floor:floor/dirt1.png
F02:floor:floor/dirt2.png
W00:wall:wall/brick_dark0.png
W01:wall:wall/brick_dark1.png
W02:wall:wall/brick_dark2.png
W03:wall:wall/brick_dark3.png
W04:wall:wall/brick_dark4.png
W05:wall:wall/brick_dark5.png
W06:wall:wall/brick_dark6.png
