# Tile configuration
# This file defines all tile classes and tile definitions.
# Its contents are shared across all map files.

CLASSES
FL:floor:false
WL:wall:true

TILES
FL00:floor:floor/dirt0.png
FL01:floor:floor/dirt1.png
FL02:floor:floor/dirt2.png
FL20:floor:floor/lava0.png
FL21:floor:floor/lava1.png
FL22:floor:floor/lava2.png
FL23:floor:floor/lava3.png
WL00:wall:wall/brick_dark0.png
WL01:wall:wall/brick_dark1.png
WL02:wall:wall/brick_dark2.png
WL03:wall:wall/brick_dark3.png
WL04:wall:wall/brick_dark4.png
WL05:wall:wall/brick_dark5.png
WL06:wall:wall/brick_dark6.png


PROPERTIES
FL20.damage=2
FL21.damage=2
FL22.damage=2
FL23.damage=2
