# Tile configuration
# This file defines all tile classes and tile definitions.
# Its contents are shared across all map files.

CLASSES
F:floor:false
W:wall:true

TILES
F00:floor:floor/dirt1.png
W00:wall:wall/brick_dark2.png
